import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Layout from "@/components/ui/Layout";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Todo Application Practice",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>
              <Toaster
            position="bottom-right"
            toastOptions={
              {
                duration: 3000,
                style: {
                  background: '#000000',
                  color: '#ffffff',
                },
              }
            }
          />
          {children}
        </Layout>
      </body>
    </html>
  );
}
